#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 06 18:46:39 WIB 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryShaders_v4.1.zip
enableShaders=false
